ci: updated ci workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,6 +15,7 @@ env:
 
 jobs:
   version:
+    name: "Check Version Increment"
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -37,13 +38,14 @@ jobs:
           if [ "$CURRENT_VERSION" = "$MAIN_VERSION" ]; then
             echo "Error: Version in package.json ($CURRENT_VERSION) has not been incremented compared to main branch ($MAIN_VERSION)."
             exit 1
-            elif [ "$HIGHEST_VERSION" != "$CURRENT_VERSION" ]; then
-          echo "Error: Version in package.json ($CURRENT_VERSION) is not the highest compared to main branch ($MAIN_VERSION)."
+          elif [ "$HIGHEST_VERSION" != "$CURRENT_VERSION" ]; then
+            echo "Error: Version in package.json ($CURRENT_VERSION) is not the highest compared to main branch ($MAIN_VERSION)."
             exit 1
-            else
+          else
             echo "Version in package.json ($CURRENT_VERSION) is higher than on the main branch ($MAIN_VERSION)."
-            fi
+          fi
   changelog:
+    name: "Check Changelog Update"
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -52,51 +54,66 @@ jobs:
           VERSION_IN_PACKAGE_JSON=$(node -p "require('./package.json').version")
 
           if ! grep -qE "# \[?$VERSION_IN_PACKAGE_JSON\]?" CHANGELOG.md; then
-          echo "Error: CHANGELOG.md has not been updated for version $VERSION_IN_PACKAGE_JSON."
-          exit 1
+            echo "Error: CHANGELOG.md has not been updated for version $VERSION_IN_PACKAGE_JSON."
+            exit 1
           else
-          echo "CHANGELOG.md has been updated for version $VERSION_IN_PACKAGE_JSON."
+            echo "CHANGELOG.md has been updated for version $VERSION_IN_PACKAGE_JSON."
           fi
   lint:
+    name: "Lint Codebase"
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - uses: actions/setup-node@v4
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
         with:
           node-version: 20
           cache: 'npm'
-      - run: npm install
-      - uses: nrwl/nx-set-shas@v4
-      - run: npx nx affected -t stylelint lint --base=origin/main --head=HEAD --exclude='*,!scope:ui,!scope:utilities'
+      - name: Install Dependencies
+        run: npm install
+      - name: Set SHAs for NX
+        uses: nrwl/nx-set-shas@v4
+      - name: Run Stylelint and Lint
+        run: npx nx affected -t stylelint lint --base=origin/main --head=HEAD --exclude='*,!scope:ui,!scope:utilities'
   format:
+    name: "Check Code Formatting"
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - uses: actions/setup-node@v4
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
         with:
           node-version: 20
           cache: 'npm'
-      - run: npm install
-      - uses: nrwl/nx-set-shas@v4
-      - run: npx nx format:check --base=origin/main --head=HEAD --projects ui utilities
+      - name: Install Dependencies
+        run: npm install
+      - name: Set SHAs for NX
+        uses: nrwl/nx-set-shas@v4
+      - name: Run Format Check
+        run: npx nx format:check --base=origin/main --head=HEAD --projects ui utilities
   build:
+    name: "Build project"
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - uses: actions/setup-node@v4
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
         with:
           node-version: 20
           cache: 'npm'
       - run: npm install
-      - uses: nrwl/nx-set-shas@v4
-      - run: npx nx affected -t build --base=origin/main --head=HEAD --exclude='*,!scope:utilities,!scope:ui' --configuration=production
+      - name: Set SHAs for NX
+        uses: nrwl/nx-set-shas@v4
+      - name: Run the building...
+        run: npx nx affected -t build --base=origin/main --head=HEAD --exclude='*,!scope:utilities,!scope:ui' --configuration=production
   test:
+    name: "Unit/Integration/UI tests"
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
